spring:
  profiles:
    active: master
  application:
    name: spring_cloud_eureka
---
spring:
   profiles: master
server:
  port:  8761
 
eureka:
  instance:
    hostname: master
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://slave:8762/eureka/
  server:
    peer-node-read-timeout-ms: 3000
    enable-self-preservation: false
---
spring:
   profiles: slave
server:
  port: 8762
 
eureka:
  instance:
    # 配置通过主机名方式注册
    hostname: slave
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://master:8761/eureka/
  server:
    peer-node-read-timeout-ms: 3000
    enable-self-preservation: false
    # 集群节点之间读取超时时间。单位：毫秒
  
 